"use client";
import { FormEvent, useEffect, useState } from "react";
import { brandConfig, prices } from "../config";

const offer={name:"Oferta de lanzamiento",price:"$150.000 CLP",features:["Diseño moderno y profesional","Responsive en todos los dispositivos","Secciones principales","Integración con WhatsApp","Enlaces a redes sociales","Formulario de contacto","SEO básico","Configuración y publicación","Ajustes finales"]};
const steps=["Oferta","Tipo de proyecto","Cotización"];

export default function QuoteFlow(){
 const [step,setStep]=useState(0);const [selected,setSelected]=useState("");const [sent,setSent]=useState(false);
 useEffect(()=>{const incoming=new URLSearchParams(window.location.search).get("servicio");if(incoming)setSelected(incoming)},[]);
 const chooseOffer=()=>{setSelected("Creación web / Oferta lanzamiento");setStep(2);window.scrollTo({top:0,behavior:"smooth"})};
 const next=()=>{if(!selected)return;setStep(2);window.scrollTo({top:0,behavior:"smooth"})};
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!e.currentTarget.checkValidity()){e.currentTarget.reportValidity();return}setSent(true);window.scrollTo({top:0,behavior:"smooth"})};
 return <main className="quote-page"><header className="quote-header"><a className="quote-logo" href="/" aria-label={`Volver al inicio de ${brandConfig.name}`}><img src={brandConfig.logo} alt={brandConfig.name}/></a><a href="/">← Volver al sitio</a></header><nav className="quote-progress" aria-label="Progreso de la cotización">{steps.map((label,i)=><div className={i===step?"active":i<step?"done":""} key={label}><span>{i<step?"✓":i+1}</span><b>{label}</b></div>)}</nav>
 {step===0&&<section className="quote-stage offer-stage"><div className="quote-offer"><div className="quote-offer-copy"><span className="offer-label">Oferta de lanzamiento FIDORIA</span><h1>Comienza tu página web por solo <em>$150.000</em></h1><p>Durante nuestros primeros 6 meses tendremos un precio especial de lanzamiento para ayudar a negocios y emprendedores a crear su presencia digital.</p><div className="quote-actions"><button className="btn" onClick={chooseOffer}>Quiero aprovechar la oferta ↗</button><button className="quote-text-button" onClick={()=>setStep(1)}>Prefiero ver otras opciones →</button></div></div><div className="quote-offer-panel"><small>PÁGINA WEB DESDE</small><div className="quote-price">$150.000 <sup>CLP</sup></div><p>Ideal para landing pages y sitios informativos de alcance definido.</p><div>{offer.features.map(x=><span key={x}>✓ {x}</span>)}</div></div><small className="quote-legal">Oferta disponible durante los primeros 6 meses desde el lanzamiento de Fidoria. Cupos y condiciones sujetos al alcance de cada proyecto. Funcionalidades especiales pueden tener un costo diferente.</small></div></section>}
 {step===1&&<section className="quote-stage plans-stage"><div className="quote-stage-head"><span className="kicker">Elige el punto de partida</span><h1>¿Qué tipo de proyecto necesitas?</h1><p>Selecciona la alternativa más cercana a tu idea. Confirmaremos contigo el alcance y el valor definitivo.</p></div><div className="quote-plans">{prices.map(p=><button className={selected===p.name?"selected":""} onClick={()=>setSelected(p.name)} key={p.name} aria-pressed={selected===p.name}><span>{selected===p.name?"✓":""}</span><h2>{p.name}</h2><strong>{p.price}</strong><ul>{p.features.map(x=><li key={x}>✓ {x}</li>)}</ul></button>)}</div><div className="quote-stage-actions"><button className="quote-back" onClick={()=>setStep(0)}>← Volver a la oferta</button><button className="btn" disabled={!selected} onClick={next}>Continuar con {selected||"mi selección"} →</button></div></section>}
 {step===2&&<section className="quote-stage form-stage">{sent?<div className="quote-success" role="status"><img src="/brand/fidoria-mark.png" alt="FIDORIA"/><span>Solicitud preparada</span><h1>Gracias por contarnos sobre tu proyecto.</h1><p>Los datos fueron validados correctamente. La conexión para enviar solicitudes reales se configurará cuando agregues un correo o WhatsApp en la configuración del sitio.</p><a className="btn" href="/">Volver al inicio</a></div>:<div className="quote-contact"><div className="quote-contact-copy"><span className="kicker">Hablemos de tu proyecto</span><h1>Tu próxima web comienza con una conversación</h1><p>Elegiste: <strong>{selected||"Proyecto por definir"}</strong>. Completa tus datos para preparar una propuesta acorde a tus objetivos.</p><div><span><i>01</i>Respuesta clara y cercana</span><span><i>02</i>Cotización según tu proyecto</span><span><i>03</i>Sin compromisos</span></div><button className="quote-back" onClick={()=>setStep(1)}>← Cambiar selección</button></div><form onSubmit={submit}><div className="form-head"><h2>Solicita tu cotización</h2><p>Completa los datos y te contactaremos.</p></div><div className="fields"><label>Nombre *<input name="name" required autoComplete="name" placeholder="Tu nombre"/></label><label>Nombre del negocio<input name="business" autoComplete="organization" placeholder="Tu negocio"/></label><label>Correo *<input name="email" type="email" required autoComplete="email" placeholder="nombre@correo.cl"/></label><label>Teléfono / WhatsApp *<input name="phone" type="tel" required autoComplete="tel" placeholder="+56 9..."/></label><label className="full">Tipo de proyecto<input name="service" value={selected} readOnly/></label><label>¿Ya posee página web? *<select name="hasWeb" required defaultValue=""><option value="" disabled>Selecciona</option><option>Sí</option><option>No</option></select></label><label>Presupuesto aproximado<select name="budget" defaultValue=""><option value="">Prefiero conversarlo</option><option>$150.000 – $250.000</option><option>$250.000 – $400.000</option><option>Más de $400.000</option></select></label><label className="full">URL actual (opcional)<input name="url" type="url" placeholder="https://..."/></label><label className="full">Descripción del proyecto *<textarea name="description" required rows={5} placeholder="Cuéntanos sobre tu negocio y lo que necesitas..."/></label><label className="consent"><input type="checkbox" required/><span>Acepto ser contactado/a por Fidoria sobre esta solicitud.</span></label></div><button className="btn submit" type="submit">Terminar y solicitar cotización ↗</button></form></div>}</section>}
 </main>
}
