import {LocalizedFooter,LocalizedHeader}from"./LocalizedChrome";
import{dictionaries,type Locale,type Dictionary}from"./config";
import{catalog,formatMoney,getProduct}from"../commerce/catalog";
import{AddToCartButton,CartPage,CheckoutPage,OrderPage,PayPalReturnPage}from"../commerce/CommerceUI";

const products=[{slug:"drive-organizer",key:"drive",type:"organizer"},{slug:"travel-console",key:"travel",type:"console"},{slug:"clean-kit",key:"clean",type:"clean"}]as const;
const split=(value:string)=>value.split("|").map((part,i)=><span key={part}>{part}{i===0&&<br/>}</span>);
function Visual({type}:{type:string}){return <div className={`product-visual ${type}`} role="img"><span>FIDORIA</span><i/><b/></div>}
function Home({locale,d}:{locale:Locale;d:Dictionary}){const p=`/${locale}`;return <main><section className="hero hero-campaign"><img className="campaign-image" src="/brand/fidoria-drive-campaign.png" alt="FIDORIA Drive organizer" fetchPriority="high"/><div className="campaign-shade"/><div className="shell campaign-content"><p className="eyebrow">{d.home.eyebrow}</p><h1>{split(d.home.title)}</h1><p className="lede">{d.home.intro}</p><div className="actions"><a className="button light-button" href={`${p}/shop`}>{d.common.collection} <span>↗</span></a><a className="campaign-link" href={`${p}/product/drive-organizer`}>{d.common.learn} →</a></div></div></section><section className="manifesto"><div className="shell"><p className="eyebrow">FIDORIA</p><h2>{split(d.home.manifesto)}</h2><p>{d.home.manifestoText}</p></div></section><section className="feature"><div className="shell feature-grid"><div className="feature-art photo-feature"><img src="/brand/fidoria-drive-campaign.png" alt="Drive Organizer" loading="lazy"/></div><div className="feature-copy"><p className="eyebrow">Drive Organizer</p><h2>{split(d.home.feature)}</h2><p>{d.home.featureText}</p><ul>{d.products.drive.features.map(x=><li key={x}>{x}</li>)}</ul><a className="button dark" href={`${p}/product/drive-organizer`}>{d.common.learn} ↗</a></div></div></section><section className="proof-strip"><div className="shell proof-grid">{d.home.benefits.map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3></article>)}</div></section><section className="collection" id="best-sellers"><div className="shell"><div className="section-head"><div><p className="eyebrow">FIDORIA Drive</p><h2>{d.home.collection}</h2></div></div><Products locale={locale} d={d}/></div></section><section className="story"><div className="shell story-grid"><div className="story-mark">F</div><div><p className="eyebrow">FIDORIA</p><h2>{split(d.home.story)}</h2><p>{d.home.storyText}</p></div></div></section><section className="newsletter"><div className="shell"><p className="eyebrow">{d.footer.journal}</p><h2>{split(d.home.newsletter)}</h2></div></section></main>}
function Products({locale,d}:{locale:Locale;d:Dictionary}){return <div className="product-grid">{products.map(item=>{const product=d.products[item.key];const commerce=getProduct(item.slug)!;return <a className="product-card" href={`/${locale}/product/${item.slug}`} key={item.slug}><Visual type={item.type}/><div><small>FIDORIA Drive</small><h3>{product.name}</h3><p>{formatMoney(commerce.price,locale)}</p></div></a>})}</div>}
function ProductPage({locale,d,slug}:{locale:Locale;d:Dictionary;slug:string}){const item=products.find(x=>x.slug===slug)||products[0];const commerce=getProduct(item.slug)??catalog[0];const product=d.products[item.key];const features="features"in product?product.features:d.products.drive.features;return <main className="subpage"><div className="shell product-page"><div className="product-gallery"><Visual type={item.type}/><p className="placeholder-note">{d.products.placeholder}</p></div><article className="product-info"><p className="eyebrow">FIDORIA Drive</p><h1>{product.name}</h1><p className="price-line">{formatMoney(commerce.price,locale)}</p><p>{product.description}</p><div className="select-row"><span className="chip">{commerce.variants[0].name}</span><span className="chip">{commerce.variants[0].sku}</span></div><AddToCartButton product={{...commerce,name:product.name,description:product.description}} locale={locale}/><ul className="product-points">{features.map(x=><li key={x}>✓ {x}</li>)}</ul></article></div></main>}
function Standard({locale,d,page}:{locale:Locale;d:Dictionary;page:keyof Dictionary["pages"]}){const content=d.pages[page];return <main className="subpage"><div className="shell"><header className="subpage-head"><p className="eyebrow">FIDORIA</p><h1 className="page-title">{content[0]}</h1><p>{content[1]}</p></header>{page==="shop"?<Products locale={locale} d={d}/>:<div className="content-grid"><article><h2>{content[0]}</h2><p>{content[1]}</p></article></div>}</div></main>}
export default function LocalizedPage({locale,slug=[]}:{locale:Locale;slug?:string[]}){const d=dictionaries[locale]||dictionaries.en;let content:React.ReactNode;const page=slug[0];if(!page)content=<Home locale={locale} d={d}/>;else if(page==="product")content=<ProductPage locale={locale} d={d} slug={slug[1]||"drive-organizer"}/>;else if(page==="cart")content=<CartPage locale={locale}/>;else if(page==="checkout"&&slug[1]==="paypal-return")content=<PayPalReturnPage locale={locale}/>;else if(page==="checkout")content=<CheckoutPage locale={locale}/>;else if(page==="order")content=<OrderPage locale={locale} orderNumber={slug[1]||""}/>;else{const supported=["shop","about","support","contact","shipping","returns","tracking","privacy","terms"] as const;content=<Standard locale={locale} d={d} page={(supported.includes(page as typeof supported[number])?page:"notFound")as keyof Dictionary["pages"]}/>};const chrome=page!=="checkout";return <>{chrome&&<LocalizedHeader locale={locale} d={d}/>} {content}{chrome&&<LocalizedFooter locale={locale} d={d}/>}</>}
