"use client";
import {useState} from "react";
import type{Dictionary,Locale}from"./config";
import LanguageSwitcher from"./LanguageSwitcher";
import{CartBagLink,CartDrawer}from"../commerce/CommerceUI";

export function LocalizedHeader({locale,d}:{locale:Locale;d:Dictionary}){
  const[open,setOpen]=useState(false);const p=`/${locale}`;
  return <><div className="announcement">{d.common.shipping} · {d.common.returns}</div><header className="header"><div className="shell nav-wrap"><a className="logo" href={p} aria-label="FIDORIA home"><img src="/brand/fidoria-monogram.svg" alt=""/><span>FIDORIA</span></a><button className="menu-button" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Menu"><i/><i/></button><nav className={open?"nav open":"nav"}><a href={`${p}/shop`}>{d.nav.shop}</a><a href={`${p}/#best-sellers`}>{d.nav.best}</a><a href={`${p}/about`}>{d.nav.about}</a><a href={`${p}/support`}>{d.nav.support}</a><a className="mobile-cart-link" href={`${p}/cart`}>{d.nav.bag}</a><div className="mobile-language"><LanguageSwitcher locale={locale} label={d.nav.language}/></div></nav><div className="nav-actions"><LanguageSwitcher locale={locale} label={d.nav.language}/><CartBagLink locale={locale}/></div></div></header><CartDrawer locale={locale}/></>;
}
export function LocalizedFooter({locale,d}:{locale:Locale;d:Dictionary}){const p=`/${locale}`;return <footer><div className="shell footer-top"><div className="footer-brand"><a className="logo" href={p}><img src="/brand/fidoria-monogram.svg" alt=""/><span>FIDORIA</span></a><p>{d.footer.line}</p></div><div><b>{d.nav.shop}</b><a href={`${p}/shop`}>{d.nav.shop}</a><a href={`${p}/#best-sellers`}>{d.nav.best}</a></div><div><b>{d.footer.help}</b><a href={`${p}/support`}>{d.nav.support}</a><a href={`${p}/shipping`}>{d.pages.shipping[0]}</a><a href={`${p}/returns`}>{d.pages.returns[0]}</a><a href={`${p}/tracking`}>{d.pages.tracking[0]}</a></div><div><b>FIDORIA</b><a href={`${p}/about`}>{d.nav.about}</a><a href={`${p}/privacy`}>{d.pages.privacy[0]}</a><a href={`${p}/terms`}>{d.pages.terms[0]}</a></div></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} FIDORIA</span><span>{locale.toUpperCase()} · {d.common.currency} $</span><span>{d.footer.journal}</span></div></footer>}
