"use client";
import { prices, siteConfig } from "../config";import { selectService } from "./Header";
const services=[
 {n:"01",kind:"creation",icon:"＋",title:"Creación web",service:"Creación web",cta:"Crear mi página",text:"Sitios creados desde cero para representar tu marca, comunicar con claridad y facilitar el contacto.",bullets:["Diseño personalizado y responsive","Formularios, WhatsApp y redes","SEO básico, velocidad y publicación"]},
 {n:"02",kind:"maintenance",icon:"◇",title:"Mantenimiento web",service:"Mantenimiento",cta:"Consultar mantenimiento",text:"Tu web al día sin que tengas que preocuparte por los detalles técnicos.",bullets:["Cambios de textos e imágenes","Corrección de errores","Pequeñas mejoras y soporte"]},
 {n:"03",kind:"redesign",icon:"↗",title:"Rediseño y actualización",service:"Rediseño",cta:"Renovar mi sitio",text:"Convertimos un sitio desactualizado en una experiencia moderna, ordenada y fácil de usar.",bullets:["Modernización visual","Mejor experiencia en celulares","Contenido y estructura optimizados"]}
];
function CreationPreview(){return <div className="service-preview creation-preview" aria-label="De wireframe inicial a sitio web terminado"><div className="preview-window"><div className="mini-browser-bar"><i/><i/><i/></div><div className="creation-wire"><span/><b/><b/><div/><div className="wire-cards"><i/><i/><i/></div></div><div className="creation-finish"><div className="finish-nav"><img src="/brand/fidoria-mark.png" alt=""/><span>FIDORIA</span><i/></div><small>DISEÑO + ESTRATEGIA</small><strong>Diseñamos experiencias web que impulsan tu negocio.</strong><button tabIndex={-1}>Conoce nuestro trabajo</button><div className="finish-panels"><i/><i/><i/></div></div><div className="creation-split"/></div></div>}
function MaintenancePreview(){const menu=["Resumen","Actualizaciones","Copias de seguridad","Seguridad","Rendimiento","Reportes"];return <div className="service-preview maintenance-preview" aria-label="Panel de mantenimiento y rendimiento del sitio"><aside><div className="dash-brand"><img src="/brand/fidoria-mark.png" alt=""/><b>FIDORIA</b></div>{menu.map((x,i)=><span className={i===0?"selected":""} key={x}><i/>{x}</span>)}</aside><div className="dash-main"><div className="dash-top"><article><small>Estado del sitio</small><b><i/> Todo en óptimas condiciones</b></article><article><small>Uptime</small><strong>99,9%</strong><svg viewBox="0 0 100 28" aria-hidden="true"><polyline points="0,23 12,17 25,20 37,11 49,18 62,7 75,15 88,12 100,2"/></svg></article></div><div className="dash-middle"><article><small>Actualizaciones al día</small><b className="status-ring">✓</b></article><article><small>Copias de seguridad al día</small><b className="cloud">⌁</b></article></div><article className="performance"><b>98<small>/100</small></b><div><span>Tiempo de carga<i/></span><span>Optimización<i/></span><span>Recursos<i/></span></div></article></div></div>}
function RedesignPreview(){return <div className="service-preview redesign-preview" aria-label="Comparación antes y después de un rediseño web"><div className="old-site"><small>ANTES</small><div className="old-nav"/><b/><b/><div className="old-image"/><i/><i/><i/></div><div className="new-site"><div className="new-nav"><img src="/brand/fidoria-mark.png" alt=""/><i/></div><small>DISEÑO WEB PROFESIONAL</small><strong>Soluciones web que impulsan negocios</strong><p>Diseño moderno, rápido y pensado para convertir.</p><button tabIndex={-1}>Ver proyectos</button><div className="new-panels"><i/><i/><i/></div></div><div className="compare-line"><span>‹›</span></div></div>}
function ServicePreview({kind}:{kind:string}){if(kind==="creation")return <CreationPreview/>;if(kind==="maintenance")return <MaintenancePreview/>;return <RedesignPreview/>}
function ServiceCard({item}:{item:typeof services[number]}){return <article className="service-card"><span className="service-number">{item.n}</span><ServicePreview kind={item.kind}/><div className="service-title"><span className="service-icon" aria-hidden="true">{item.icon}</span><h3>{item.title}</h3></div><p>{item.text}</p><ul>{item.bullets.map(x=><li key={x}><i>✓</i>{x}</li>)}</ul><a href="#contacto" onClick={()=>selectService(item.service)}><span>{item.cta}</span><b aria-hidden="true">→</b></a></article>}
export function Intro(){return <section className="section intro"><div className="container split"><span className="kicker">Presencia que inspira confianza</span><div><h2>Tu negocio merece una página web <em>profesional</em></h2><p>Tu página suele ser el primer contacto de un potencial cliente con tu negocio. En Fidoria creamos sitios que transmiten confianza, presentan tus servicios de forma clara y hacen que contactarte sea simple.</p><div className="intro-points"><span>▣ Responsive</span><span>⌁ SEO inicial</span><span>↗ Contacto directo</span></div></div></div></section>}
export function Services(){return <section className="section shade services-section" id="servicios"><div className="container"><div className="section-head"><div><span className="kicker">Lo que hacemos</span><h2>Soluciones web para cada etapa</h2></div><p>Desde tu primera página hasta la evolución de un sitio existente, avanzamos contigo.</p></div><div className="service-grid">{services.map(s=><ServiceCard item={s} key={s.title}/>)}</div></div></section>}
export function LaunchOffer(){const items=["Diseño moderno y profesional","Responsive en todos los dispositivos","Secciones principales","Integración con WhatsApp","Enlaces a redes sociales","Formulario de contacto","SEO básico","Configuración y publicación","Ajustes finales"];return <section className="section"><div className="container offer"><div className="offer-copy"><span className="offer-label">Oferta de lanzamiento FIDORIA</span><h2>Comienza tu página web por solo <em>$150.000</em></h2><p>Durante nuestros primeros 6 meses tendremos un precio especial de lanzamiento para ayudar a negocios y emprendedores a crear su presencia digital.</p><a className="btn light" href="/cotizar" onClick={()=>selectService("Creación web / Oferta lanzamiento")}>Quiero aprovechar la oferta ↗</a></div><div className="offer-panel"><small>PÁGINA WEB DESDE</small><div className="price">$150.000 <sup>CLP</sup></div><p className="offer-ideal">Ideal para landing pages y sitios informativos de alcance definido.</p><div className="offer-list">{items.map(x=><span key={x}>✓ {x}</span>)}</div></div><p className="legal">Oferta disponible durante los primeros 6 meses desde el lanzamiento de Fidoria. Cupos y condiciones sujetos al alcance de cada proyecto. Funcionalidades especiales, tiendas online, sistemas de reservas u otros desarrollos adicionales pueden tener un costo diferente.</p></div></section>}
const benefits=[["✦","Diseño moderno","Una imagen profesional alineada con tu negocio."],["▣","Adaptado a celulares","Se ve y funciona bien en cualquier pantalla."],["↗","Contacto directo","Rutas claras para convertir visitas en consultas."],["◇","Desarrollo personalizado","Decisiones pensadas para tus objetivos reales."],["◌","Soporte y mantenimiento","Acompañamiento para seguir mejorando."]];
export function Benefits(){return <section className="section shade"><div className="container"><div className="center"><span className="kicker">Por qué Fidoria</span><h2>Más que una web bonita</h2><p>Creamos una herramienta clara, funcional y preparada para hacer crecer tu presencia digital.</p></div><div className="benefits">{benefits.map(([i,t,p])=><article key={t}><span>{i}</span><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>}
const steps=[["01","Conocemos tu proyecto","Escuchamos tu idea, negocio y objetivos."],["02","Planificamos","Ordenamos contenidos, estructura y alcance."],["03","Diseñamos y desarrollamos","Creamos una experiencia clara y moderna."],["04","Revisamos","Afinamos juntos los detalles finales."],["05","Publicamos","Dejamos tu sitio listo para salir al mundo."],["06","Seguimos contigo","Te apoyamos con mantenimiento y mejoras."]];
export function Process(){return <section className="section process-section"><div className="container"><div className="section-head"><div><span className="kicker">Cómo trabajamos</span><h2>Un proceso claro, de <em>principio a fin</em></h2></div><p>Sin complicaciones innecesarias. Sabes qué estamos haciendo y qué viene después.</p></div><div className="process">{steps.map(([n,t,p],i)=><article style={{animationDelay:`${i*90}ms`}} key={n}><span>{n}</span><div/><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>}
const projects=[
 {title:"Club de Boxeo YTZ",image:"/projects/club-boxeo-ytz.png",alt:"Página de inicio del sitio web Club de Boxeo YTZ",desc:"Sitio web diseñado para presentar el club, comunicar entrenamientos y proyectar una identidad fuerte, profesional y coherente con el mundo del boxeo.",tags:["Sitio corporativo","Deporte","Branding"]},
 {title:"Estilo Timbres",image:"/projects/estilo-timbres.png",alt:"Página de inicio del e-commerce Estilo Timbres",desc:"E-commerce desarrollado para presentar y vender timbres personalizados, con una experiencia visual cálida, clara y enfocada en facilitar la compra.",tags:["E-commerce","Personalización","Emprendimiento"]}
];
export function Portfolio(){return <section className="section shade portfolio" id="proyectos"><div className="container"><header className="portfolio-head"><div><span className="kicker">Proyectos realizados</span><h2>Proyectos terminados que muestran lo que podemos crear para tu marca</h2></div><p>Sitios web reales, diseñados y desarrollados con estrategia, experiencia de usuario y atención al detalle. Cada proyecto refleja nuestro compromiso con la calidad y los resultados.</p></header><div className="portfolio-grid">{projects.map(p=><article className="portfolio-card" key={p.title}><div className="portfolio-image"><img src={p.image} alt={p.alt}/></div><div className="portfolio-copy"><span className="real-badge">✓ Proyecto real</span><h3>{p.title}</h3><p>{p.desc}</p><div className="portfolio-tags" aria-label={`Características de ${p.title}`}>{p.tags.map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div></div></section>}
export function Maintenance(){return <section className="section"><div className="container maintenance"><div><span className="kicker">Tu web sigue avanzando</span><h2>Mantén tu página siempre actualizada</h2><p>Fidoria puede encargarse de cambios de información, imágenes, servicios, nuevas secciones y mejoras generales para que tu sitio acompañe el crecimiento de tu negocio.</p><a className="btn" href="#contacto" onClick={()=>selectService("Mantenimiento")}>Consultar mantenimiento ↗</a></div><div className="maintenance-art"><div className="update-card"><div className="update-top"><span>Panel de mantenimiento</span><b>FIDORIA</b></div><h3>Tu sitio está al día</h3><div className="update-states"><span>✓ Contenido actualizado</span><span>✓ Errores corregidos</span><span>✓ Mejoras aplicadas</span></div><div className="progress"><i/></div></div><div className="status">✓ Revisión completada</div></div></div></section>}
export function Pricing(){return <section className="section shade" id="planes"><div className="container"><div className="center"><span className="kicker">Valores orientativos</span><h2>Una solución para cada necesidad</h2><p>Cada proyecto es distinto. Estos valores “desde” sirven como referencia inicial y se confirman según el alcance.</p></div><div className="pricing">{prices.map((p,i)=><article className={i===0?"featured":""} key={p.name}>{i===0&&<span className="recommended">OFERTA DE LANZAMIENTO</span>}<h3>{p.name}</h3><small>{p.name==="Rediseño"?"VALOR":"DESDE"}</small><div>{p.price}</div><ul>{p.features.map(x=><li key={x}>✓ {x}</li>)}</ul><a href="#contacto" onClick={()=>selectService(p.name.includes("Mantenimiento")?"Mantenimiento":p.name==="Rediseño"?"Rediseño":"Creación web")}>Cotizar proyecto →</a></article>)}</div><p className="price-note">Valores desde / sujetos al alcance del proyecto. Durante los primeros 6 meses, la creación web seleccionada parte desde $150.000 CLP como oferta de lanzamiento.</p></div></section>}
export function FinalCTA(){const wa=siteConfig.whatsappNumber?`https://wa.me/${siteConfig.whatsappNumber}`:"/cotizar";return <section className="section final-cta-section"><div className="container final-cta"><div><span className="kicker">Demos el próximo paso</span><h2>¿Listo para darle vida a tu próxima página web?</h2><p>Cuéntanos sobre tu proyecto y descubre cómo Fidoria puede ayudarte a crear una presencia digital profesional.</p></div><div className="actions"><a className="btn" href="/cotizar">Solicitar cotización ↗</a><a className="btn ghost" href={wa}>{siteConfig.whatsappNumber?"Hablar por WhatsApp":"Comenzar cotización"}</a></div></div></section>}
