import Header from "./components/Header";
import Footer from "./components/Footer";

const products = [
  { slug: "drive-organizer", name: "Drive Organizer", price: "$49.00", type: "organizer", note: "Best seller" },
  { slug: "travel-console", name: "Travel Console", price: "$39.00", type: "console", note: "New" },
  { slug: "clean-kit", name: "Compact Clean Kit", price: "$32.00", type: "clean", note: "Everyday essential" },
];
function ProductVisual({type}:{type:string}) { return <div className={`product-visual ${type}`} role="img" aria-label={`${type} product photography placeholder`}><span>FIDORIA</span><i/><b/></div> }
export default function Home(){return <><Header/><main>
  <section className="hero hero-campaign" id="top"><img className="campaign-image" src="/brand/fidoria-drive-campaign.png" alt="FIDORIA Drive organizer in a modern car interior" fetchPriority="high"/><div className="campaign-shade"/><div className="shell campaign-content"><p className="eyebrow">FIDORIA / DRIVE 001</p><h1>Every journey,<br/><em>considered.</em></h1><p className="lede">Quietly useful objects for a life in motion.</p><div className="actions"><a className="button light-button" href="/shop">Explore the collection <span>↗</span></a><a className="campaign-link" href="/product/drive-organizer">Discover Drive 001 <span>→</span></a></div></div><div className="campaign-meta"><span>Designed for the everyday</span><span>01 — 04</span><span>Scroll to discover ↓</span></div></section>
  <div className="ticker" aria-hidden="true"><div>USEFUL BY DESIGN <i/> MADE FOR MOVEMENT <i/> CONSIDERED ESSENTIALS <i/> FIDORIA DRIVE <i/> USEFUL BY DESIGN <i/> MADE FOR MOVEMENT</div></div>
  <section className="manifesto" id="philosophy"><div className="shell"><p className="eyebrow">Our point of view</p><h2>Small upgrades.<br/>Better experiences.</h2><p>We look for products that solve real friction—quietly, beautifully, and without adding complexity.</p></div></section>
  <section className="feature"><div className="shell feature-grid"><div className="feature-art photo-feature"><img src="/brand/fidoria-drive-campaign.png" alt="Drive Organizer shown in use" loading="lazy"/><span className="measure m1">01 / In context</span><span className="measure m2">Designed for motion</span></div><div className="feature-copy"><p className="eyebrow">The Drive Organizer</p><h2>Calm, even<br/>on the move.</h2><p>A considered place for the things you reach for most. Structured storage, easy access, less visual noise.</p><ul><li>Flexible compartments</li><li>Secure, stable construction</li><li>Clean, understated finish</li></ul><a className="button dark" href="/product/drive-organizer">Discover the organizer <span>↗</span></a></div></div></section>
  <section className="proof-strip"><div className="shell proof-grid"><article><b>01</b><h3>Useful by design</h3><p>Every product starts with a real, everyday need.</p></article><article><b>02</b><h3>Selected with care</h3><p>Quality, function and simplicity—nothing extra.</p></article><article><b>03</b><h3>Made for movement</h3><p>Practical essentials for wherever life takes you.</p></article><article><b>04</b><h3>Human support</h3><p>Clear answers before and after your order.</p></article></div></section>
  <section className="transformation"><div className="shell"><div className="section-head"><div><p className="eyebrow">One simple change</p><h2>From cluttered<br/>to considered.</h2></div><p>Less time searching. More space to focus on the road ahead.</p></div><div className="before-after"><div className="scene before"><span>Before</span><i/><i/><i/><i/></div><div className="transform-mark"><b>F</b><small>FIDORIA</small></div><div className="scene after"><span>After</span><div className="mini-organizer"><i/><i/><i/></div></div></div></div></section>
  <section className="collection" id="best-sellers"><div className="shell"><div className="section-head"><div><p className="eyebrow">The collection</p><h2>Made for the everyday.</h2></div><a className="text-link" href="/shop">View all products <span>↗</span></a></div><div className="product-grid">{products.map(p=><a className="product-card" href={`/product/${p.slug}`} key={p.slug}><ProductVisual type={p.type}/><div><small>{p.note}</small><h3>{p.name}</h3><p>{p.price} USD</p></div></a>)}</div></div></section>
  <section className="story"><div className="shell story-grid"><div className="story-mark">F</div><div><p className="eyebrow">Why FIDORIA</p><h2>Better is often<br/>beautifully simple.</h2><p>FIDORIA is built around a straightforward idea: the objects we use every day should work better, look considered, and last beyond the moment.</p><a className="text-link" href="/about">Our approach <span>↗</span></a></div></div></section>
  <section className="faq-section"><div className="shell faq-grid"><div><p className="eyebrow">Good to know</p><h2>Clear answers.</h2><p>No fine print hidden behind the experience.</p></div><div className="faq-list">{[["Where do you ship?","We are preparing tracked delivery for the United States, Canada, the United Kingdom and Australia. Availability is confirmed at checkout."],["How can I track my order?","Once your order ships, you’ll receive an email with a tracking link."],["What is your return policy?","Eligible unused items can be returned within 30 days of delivery. See our Returns page for conditions."],["Which payments do you accept?","Available secure payment methods are shown at checkout. We never store full card details."],["How do I reach support?","Use our contact page and our team will help with product or order questions."]].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>
  <section className="newsletter"><div className="shell"><p className="eyebrow">FIDORIA Journal</p><h2>Useful things,<br/>occasionally.</h2><p>Product notes, practical ideas and considered releases.</p><form><label className="sr-only" htmlFor="email">Email address</label><input id="email" type="email" placeholder="Email address" required/><button type="submit">Join the journal ↗</button></form><small>By subscribing, you agree to our Privacy Policy.</small></div></section>
  </main><Footer/></>}
